apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: mesoor
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: kibana
        image: harbor.nadileaf.com/boe/kibana:6.3.2
        env:
        - name: "CLUSTER_NAME"
          value: "knx"
        - name: XPACK_SECURITY_ENABLED
          value: 'false'
        - name: XPACK_GRAPH_ENABLED
          value: 'false'
        - name: XPACK_ML_ENABLED
          value: 'false'
        - name: XPACK_REPORTING_ENABLED
          value: 'false'
        - name: ELASTICSEARCH_URL
          value: 'http://entity-elasticsearch-master.mesoor.svc:9200'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: mesoor
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP