apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesoor-db
  namespace: mesoor
spec:
  selector:
    matchLabels:
      app: mesoor-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mesoor-db
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1q2w3e4r"
        ports:
        - containerPort: 3306
          name: mesoor-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mesoor-db-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mesoor-db-pv-claim
  namespace: mesoor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mesoor-db
  namespace: mesoor
spec:
  ports:
  - port: 3306
  selector:
    app: mesoor-db